import { components } from '../data/components/index.js';
import { Page, demo, icon } from './shell.js';
import { escapeHtml } from '../lib/markdown.js';

export function supportPage(): Page {
  const p = new Page({ file: 'support.html', title: 'Implementation & integration', eyebrow: 'Reference', lead: 'Choose components using their implemented behavior, dependencies and application responsibilities.' });
  p.section('Integration contract', `<div class="sk-prose"><p>Load <code>sekura.css</code>, then the behavior bundle and call <code>Sekura.autoEnhance()</code> after the markup exists. Use <code>dispose(root)</code> before replacing manually managed content. Framework recipes include lifecycle cleanup and native markup.</p><p>The framework outputs are editable reference recipes. Application data, permissions, network requests and action outcomes remain yours. The component specification’s props describe the intended API; they are not automatically props on every recipe.</p><p>For selective CSS loading, read <a class="sk-link" href="assets/component-manifest.json">the machine-readable component manifest</a>. It lists the actual root class, CSS dependencies and controller. Load tokens and base styles first. The full stylesheet includes all dependencies.</p></div>`);
  p.section('Native React controls', `<div class="sk-prose"><p>Build <code>@sekura/react</code> with <code>npm run build:react</code> and install the local <code>dist-react</code> package. Its versioned native API exports Button, TextField, Textarea, Select, Checkbox and Switch. Fields accept label, hint and error; native props and refs are forwarded. Applications own controlled values and outcomes. Load the matching Sekura CSS. Other components remain editable recipes.</p></div>`);
  p.section('Structured integration checks', `<div class="sk-prose"><p><code>get_component_code</code> preserves its text response and adds an output schema with structured code, stylesheet dependencies, event payloads and initialization instructions. <code>validate_integration</code> accepts component IDs, markup, loaded stylesheets, initialization mode, declared controllers and handled events. It checks ID targets, native elements, icons and dependencies together. Declared handlers still require runtime tests.</p><p>For example, declare <code>handledEvents: ["button:click"]</code> when your application wires the save action. A warning identifies missing declarations; it cannot inspect callback correctness.</p></div>`);
  p.section('Design-tool starter library', `<div class="sk-prose"><p>Run <code>npm run build:design-kit</code> after emitting CSS to generate an importable Figma development plugin in <code>dist-design-kit</code>. It creates six editable control sets with 216 theme, density and state variants, plus basic button and toggle prototype transitions. Appearance derives from the shipped CSS; manual Figma review is required before team-library publication.</p><p>Use the <a href="form-lab.html">form composition lab</a> to check async validation, translated labels, dependent fields, permission changes and real HTTP requests. Chromium, Firefox and WebKit exercise representative workflows; screen-reader and physical-device acceptance still needs a person.</p></div>`);
  p.section('Component support', `<div class="sk-table" role="region" aria-label="Component implementation support" tabindex="0"><table><thead><tr><th scope="col">Component</th><th scope="col">Root class</th><th scope="col">Behavior</th><th scope="col">CSS dependencies</th></tr></thead><tbody>${components.map(c => `<tr><th scope="row"><a class="sk-link" href="component-${c.id}.html">${c.name}</a></th><td><code>${c.implementation!.rootClass}</code></td><td>${c.implementation!.controller ?? c.implementation!.behavior}</td><td>${c.implementation!.cssDependencies.join(', ') || 'Base styles only'}</td></tr>`).join('')}</tbody></table></div>`);
  p.section('Boundaries to plan for', `<ul class="sk-prose"><li>Tree behavior supports single selection, tri-state multi-selection and cancellable lazy loading. Supply rendered child treeitems through <code>loadChildren(item, signal)</code>; keep permissions in your application.</li><li>Combobox <code>loadOptions(query, signal)</code> and command-palette <code>sources</code> handle async results, cancellation and errors. Supply the search provider; execute selected commands in your application.</li><li>Upload controls validate and select files. Supply an upload callback for transport; the workbench demonstrates progress, retry and cancellation with an explicit simulator.</li><li>Pagination belongs to the list’s filter and selection model. The projects example implements that model locally.</li><li>Persisted switches require an async onToggle callback. A native switch without that callback changes local form state only.</li><li>Full-page recipes contain placeholder regions intended for composition. Replace those with your navigation and content.</li></ul>`);
  p.section('Advanced controller contracts', `<div class="sk-prose"><p>Use <code>createRangeSlider(root)</code> for a <code>.sk-slider--range</code> containing two separately labelled native ranges. Link exact number inputs with <code>data-sk-slider-value="range-id"</code>. The bounds cannot cross; <code>values</code> and <code>sk:slider:range-change</code> expose the pair.</p><p>For multi-select comboboxes use <code>.sk-combobox--multi</code>, a <code>.sk-combobox__field</code> wrapper and <code>multiple: true</code>. Read IDs with <code>values</code> or <code>sk:combobox:change</code>; tokens are controller-owned. Single selection still writes the value to the input unless <code>displayLabel: true</code> is set.</p><p>Initialize each element once. A custom tree provider uses <code>data-sk-custom-tree</code>; custom uploads use <code>data-sk-custom-upload</code>; manually initialized sliders use <code>data-sk-custom-slider</code> on their root. Omit automatic markers on manually initialized comboboxes and palettes. Call each controller’s <code>destroy()</code> before unmounting. Auto-enhanced palettes accept <code>data-sk-palette-open="palette-id"</code>; global shortcuts require explicit <code>data-sk-palette-shortcut="Mod+K"</code>. Prefix scoping belongs to the command provider, as demonstrated in the workbench.</p><p>Static workspace compositions use native articles, headers, lists and status messages. The application owns save transitions and conflict recovery; loading never means content was persisted.</p></div>`);
  p.section('For designers, developers and agents', `<div class="sk-prose"><p>Designers: use the <a class="sk-link" href="workbench.html">workbench</a> to compare sizes, densities, states and long labels. Check actual keyboard flow, errors and recovery as part of the design.</p><p>Developers: preserve native elements and controller markers, assign unique IDs, let one layer own ARIA state, and wire application outcomes explicitly. Use the compiled recipes as starting points.</p><p>AI agents: read implementation metadata before promising a behavior. Use the exact root class, include dependencies, distinguish local simulation from persistence, and validate both markup and interactions. A successful markup lint does not prove actions work.</p></div>`);
  return p;
}

export function workbenchPage(): Page {
  const p = new Page({ file: 'workbench.html', title: 'Component workbench', eyebrow: 'Examples', lead: 'Compare control alignment and try complete action states before composing a page.' });
  p.section('Appearance controls', `<div class="sk-field-row">
    <div class="sk-field"><label class="sk-field__label" for="bench-theme">Preview theme</label><select class="sk-select sk-field__control" id="bench-theme" data-sk-bench-theme><option>light</option><option>dark</option><option>hc-light</option><option>hc-dark</option></select></div>
    <div class="sk-field"><label class="sk-field__label" for="bench-density">Preview density</label><select class="sk-select sk-field__control" id="bench-density" data-sk-bench-density><option>comfortable</option><option>compact</option><option>dense</option></select></div>
    <div class="sk-field"><label class="sk-field__label" for="bench-state">Preview state</label><select class="sk-select sk-field__control" id="bench-state" data-sk-bench-state><option value="rest">Rest</option><option value="disabled">Disabled</option><option value="busy">Busy</option><option value="invalid">Invalid</option><option value="readonly">Read only</option></select></div>
    <div class="sk-field-row__actions"><label class="sk-checkbox"><input type="checkbox" class="sk-checkbox__input" data-sk-bench-long /><span class="sk-checkbox__box" aria-hidden="true"></span><span>Long labels</span></label></div>
  </div>`);
  p.section('Control sizing', `<div class="sk-stack sk-stack--gap-24 docs-workbench" data-sk-bench-preview data-sk-theme="light" data-sk-density="comfortable">${['sm', 'md', 'lg'].map(size => {
    const suffix = size === 'md' ? '' : ` sk-input--${size}`;
    return `<div class="sk-stack sk-stack--gap-8"><h3>${size === 'sm' ? 'Small' : size === 'md' ? 'Medium' : 'Large'}</h3><div class="docs-control-row" data-sk-size-row="${size}">
      <button type="button" class="sk-button sk-button--primary${size === 'md' ? '' : ` sk-button--${size}`}" data-sk-bench-button>Save changes</button>
      <input class="sk-input${suffix}" aria-label="${size} project name" value="Website redesign" />
      <select class="sk-select${size === 'md' ? '' : ` sk-select--${size}`}" aria-label="${size} team"><option>Product team</option><option>Platform team</option></select>
      <div class="sk-number sk-input-group${size === 'md' ? '' : ` sk-field--${size}`}" data-sk-bench-number><input class="sk-input" aria-label="${size} target length" data-sk-number min="1" max="260" value="45" /><span class="sk-number__steppers"><button type="button" class="sk-number__step" data-sk-step="-1" aria-hidden="true" tabindex="-1">−</button><button type="button" class="sk-number__step" data-sk-step="1" aria-hidden="true" tabindex="-1">+</button></span></div>
    </div><p class="sk-field__hint" data-sk-state-help>Use Tab to inspect focus. Controls share the same target height.</p></div>`;
  }).join('')}</div>`);
  p.section('Menu and open documents', `<p>Menu destinations stay in place. Currently open documents appear in their own section below the divider. They are not children of the last menu item. Expand Projects or follow a link to try the example pages.</p>
  <div class="sk-card" style="max-inline-size:var(--sk-layout-nav-width)"><div class="sk-card__body">
    <nav aria-label="Workspace navigation example" data-sk-open-items-example>
      <h3 class="sk-side-nav__group-label" id="bench-menu-heading">Menu</h3>
      <ul class="sk-side-nav__list" aria-labelledby="bench-menu-heading">
        <li><a class="sk-side-nav__item" href="example-dashboard.html">${icon('home')}<span class="sk-side-nav__label">Overview</span></a></li>
        <li><div class="sk-side-nav__branch-row"><a class="sk-side-nav__item" href="example-list.html">${icon('globe')}<span class="sk-side-nav__label">Projects</span></a><button class="sk-side-nav__toggle" type="button" data-sk-disclosure="bench-project-pages" aria-controls="bench-project-pages" aria-expanded="true" aria-label="Project pages">${icon('chevron-down', 16)}</button></div>
          <ul class="sk-side-nav__children" id="bench-project-pages" aria-label="Project pages"><li><a class="sk-side-nav__item" href="example-form.html"><span class="sk-side-nav__label">Create project</span></a></li><li><a class="sk-side-nav__item" href="example-detail.html"><span class="sk-side-nav__label">Project activity</span></a></li></ul>
        </li>
      </ul>
      <section class="sk-side-nav__open-items" aria-labelledby="bench-open-heading">
        <h3 class="sk-side-nav__group-label" id="bench-open-heading">Open items</h3>
        <ul class="sk-side-nav__list" aria-labelledby="bench-open-heading">
          ${[['example-workspace.html', 'Document workspace'], ['example-detail.html', 'Website redesign']].map(([href, title]) => `<li><a class="sk-side-nav__item" href="${href}"><svg aria-hidden="true" focusable="false" width="20" height="20" viewBox="0 0 20 20"><path d="M5 2h7l4 4v12H5z M12 2v4h4 M8 10h5 M8 13h5" fill="none" stroke="currentColor" stroke-width="1.5" /></svg><span class="sk-side-nav__label">${title}</span></a></li>`).join('')}
        </ul>
      </section>
    </nav>
  </div></div><p>The application owns which documents are open. Opening or closing a menu branch never closes a document. When a document is active, mark its exact link with <code>aria-current="page"</code>; keep section links in a separate “On this page” navigation.</p>`);
  p.section('Filter and comparison alignment', `<p>Explanations sit below labels, before controls. The permanent arrow identifies project suggestions without hovering. These forms use local example values only.</p>
  <form class="sk-field-row" data-sk-alignment-filters>
    <div class="sk-field"><label class="sk-field__label" for="bench-project-key">Project key (exact)</label><p class="sk-field__hint" id="bench-project-key-hint">Choose an exact key from the suggestions.</p><input class="sk-input sk-field__control" id="bench-project-key" name="project" list="bench-project-keys" aria-describedby="bench-project-key-hint" placeholder="All projects" /><datalist id="bench-project-keys"><option value="SekuraDesignMCP"></option><option value="SekuraAgentPlanner"></option></datalist></div>
    <div class="sk-field"><label class="sk-field__label" for="bench-run-query">Search runs</label><input class="sk-input sk-field__control" id="bench-run-query" name="query" type="search" placeholder="Revision or target" /></div>
    <div class="sk-field"><label class="sk-field__label" for="bench-run-from">From (UTC)</label><input class="sk-input sk-field__control" id="bench-run-from" name="from" type="date" /></div>
    <div class="sk-field-row__actions"><div class="sk-field-row__action-group"><button class="sk-button sk-button--primary" type="submit">Apply filters</button><button class="sk-button sk-button--ghost" type="reset">Reset</button></div></div>
  </form><p role="status" data-sk-alignment-filter-state>No filters applied.</p>
  <section class="sk-page-header sk-page-header--section" aria-labelledby="bench-compare-title" data-sk-alignment-header><div class="sk-page-header__main">
    <div class="sk-page-header__titles"><h3 class="sk-page-header__title" id="bench-compare-title">Compare two runs</h3><p class="sk-page-header__description">Choose the earlier and later run. The description stays with its heading while fields and buttons share a control row.</p></div>
    <form class="sk-field-row sk-page-header__controls" data-sk-alignment-compare>
      <div class="sk-field"><label class="sk-field__label" for="bench-baseline">Baseline (earlier)</label><input class="sk-input sk-field__control" id="bench-baseline" name="baseline" value="run-001" required /></div>
      <div class="sk-field"><label class="sk-field__label" for="bench-candidate">Candidate (later)</label><input class="sk-input sk-field__control" id="bench-candidate" name="candidate" value="run-002" required /></div>
      <div class="sk-field-row__actions"><div class="sk-field-row__action-group"><button class="sk-button sk-button--primary" type="submit">Compare runs</button><button class="sk-button sk-button--secondary" type="reset">Reset selection</button></div></div>
    </form>
  </div></section><p role="status" data-sk-alignment-compare-state>No comparison selected.</p>`);
  p.section('Save, fail, cancel and retry', `<div class="sk-card"><div class="sk-card__body sk-stack sk-stack--gap-16" data-sk-action-example>
    <p>This operation uses a local simulator. Successful saves increase the version; Undo restores it.</p>
    <label class="sk-checkbox"><input class="sk-checkbox__input" type="checkbox" data-sk-fail-next /><span class="sk-checkbox__box" aria-hidden="true"></span><span>Fail the next request</span></label>
    <div class="sk-cluster sk-cluster--gap-8"><button class="sk-button sk-button--primary" type="button" data-sk-action-save>Save changes</button><button class="sk-button sk-button--secondary" type="button" data-sk-action-cancel disabled>Cancel saving</button><button class="sk-button sk-button--secondary" type="button" data-sk-action-retry hidden>Retry save</button></div>
    <p role="status" data-sk-action-status>Version 0. Ready to save.</p>
  </div></div>`);
  const upload = components.find(c => c.id === 'file-upload')!;
  p.section('Upload queue', `<p class="sk-prose">Local upload simulator: no files leave your device. Choose files, cancel an upload, or force a failure and retry.</p><label class="sk-checkbox"><input class="sk-checkbox__input" type="checkbox" data-sk-upload-fail /><span class="sk-checkbox__box" aria-hidden="true"></span><span>Fail uploads until unchecked</span></label>${demo(upload.html.replace('class="sk-upload"', 'class="sk-upload" data-sk-custom-upload'), upload.html)}`);
  p.section('Compact file selection', `<div class="sk-upload sk-upload--compact"><input class="sk-upload__input sk-visually-hidden" type="file" id="bench-compact-file" accept=".csv" aria-describedby="bench-compact-help" /><div class="sk-upload__zone"><label class="sk-button sk-button--secondary" for="bench-compact-file">Choose CSV file</label><p class="sk-upload__constraints" id="bench-compact-help">CSV, up to 10 MB. Selection only; no upload transport is configured.</p></div><ul class="sk-upload__list" aria-label="Selected CSV file"></ul></div>`);
  p.section('Multi-select and async search', `<div class="sk-stack sk-stack--gap-16" id="bench-advanced">
    <p>Local search simulation. Choose multiple tags or add your own. For async search, type <strong>error</strong> to exercise recovery; typing another query retries.</p>
    <div class="sk-field"><label class="sk-field__label" for="bench-tags">Project tags</label>
    <p class="sk-field__hint" id="bench-tags-help">Enter selects a suggestion or adds your text. Backspace in an empty field removes the last tag.</p><div class="sk-combobox sk-combobox--multi"><div class="sk-combobox__field"><input class="sk-input" id="bench-tags" aria-describedby="bench-tags-help" /></div><ul class="sk-combobox__list" id="bench-tags-list" aria-label="Available project tags"><li class="sk-combobox__option" role="option" data-value="design">Design</li><li class="sk-combobox__option" role="option" data-value="engineering">Engineering</li><li class="sk-combobox__option" role="option" aria-disabled="true">Restricted</li></ul></div><p role="status" id="bench-tags-state">No tags selected.</p></div>
    <div class="sk-field"><label class="sk-field__label" for="bench-async">Find a contributor</label><div class="sk-combobox sk-combobox--async"><input class="sk-input" id="bench-async" /><ul class="sk-combobox__list" id="bench-async-list" aria-label="Contributors"></ul></div><p role="status" id="bench-async-state">No contributor selected.</p></div>
  </div>`);
  p.section('Range with exact entry', `<form id="bench-range-form"><fieldset class="sk-fieldset"><legend class="sk-field__label">Estimated hours</legend><div class="sk-slider sk-slider--range" id="bench-range">
    <div class="sk-slider__bound"><label class="sk-field__label" for="bench-range-min">Minimum hours</label><input class="sk-slider__input" id="bench-range-min" type="range" min="0" max="100" step="1" value="20" /><input class="sk-input sk-slider__number" type="number" aria-label="Exact minimum hours" data-sk-slider-value="bench-range-min" min="0" max="100" value="20" /></div>
    <div class="sk-slider__bound"><label class="sk-field__label" for="bench-range-max">Maximum hours</label><input class="sk-slider__input" id="bench-range-max" type="range" min="0" max="100" step="1" value="80" /><input class="sk-input sk-slider__number" type="number" aria-label="Exact maximum hours" data-sk-slider-value="bench-range-max" min="0" max="100" value="80" /></div>
  </div><p class="sk-field__hint">Both thumbs have their own label. Exact entries are clamped to preserve the span.</p><button class="sk-button sk-button--secondary" type="reset">Reset hours</button></fieldset></form>`);
  p.section('Lazy tree with tri-state selection', `<div class="sk-stack sk-stack--gap-12"><p>Local lazy-loading simulation. Expand the team using its chevron or Arrow Right. Space selects a scope; parents reflect partially selected descendants.</p><label class="sk-checkbox"><input class="sk-checkbox__input" type="checkbox" id="bench-tree-fail" /><span class="sk-checkbox__box" aria-hidden="true"></span><span>Fail the next expansion</span></label><ul class="sk-tree sk-tree--multi" id="bench-tree" data-sk-custom-tree role="tree" aria-label="Project permissions"><li class="sk-tree__item" role="treeitem" aria-expanded="false" data-sk-loadable data-value="team" tabindex="0"><span class="sk-tree__row"><svg class="sk-tree__chevron" aria-hidden="true" width="16" height="16"><use href="#sk-icon-chevron-down" /></svg><span class="sk-tree__label">Product team</span></span></li></ul><p role="status" id="bench-tree-state">No permissions selected.</p></div>`);
  p.section('Async command palette', `<p>Local commands demonstrate loading, no matches, failure and session recents. Type <strong>&gt;</strong> to scope to actions, or <strong>error</strong> to simulate a failed provider. Selection updates the status below.</p><button class="sk-button sk-button--secondary" type="button" id="bench-palette-open">Search example commands</button><p id="bench-palette-state" role="status">No command selected.</p><div class="sk-command-palette" id="bench-palette" role="dialog" aria-modal="true" aria-label="Example commands" hidden><div class="sk-command-palette__panel"><div class="sk-command-palette__search"><input class="sk-command-palette__input" aria-label="Search example commands" placeholder="Search or type > for actions" /><button type="button" class="sk-button sk-button--ghost sk-button--sm" data-sk-palette-close>Close</button></div><div class="sk-command-palette__results" role="listbox" aria-label="Example command results"></div><p class="sk-visually-hidden" role="status"></p></div></div>`);
  p.section('Workspace and timeline states', `<p>State references below are illustrative. The <a class="sk-link" href="example-workspace.html">workspace example</a> exercises document width, wrapping context actions, local checkpoints and recent activity.</p><div class="sk-cluster sk-cluster--gap-16">${[['pending', 'Unsaved changes'], ['saving', 'Saving…'], ['saved', 'Saved to the server'], ['local', 'Saved on this device'], ['error', 'Save failed. Retry available.'], ['conflict', 'Newer revision available. Review changes.']].map(([state, text]) => `<p class="sk-save-state" data-state="${state}"><span class="sk-save-state__indicator" aria-hidden="true"></span>${text}</p>`).join('')}</div>
    <h3>Empty activity</h3><ul class="sk-activity-list" aria-label="Recent activity example"><li class="sk-activity-list__empty">No recent documents. <a class="sk-link" href="example-workspace.html">Open the handbook</a> to begin.</li></ul>
    <div class="sk-timeline--grouped"><section aria-labelledby="bench-day"><h3 class="sk-timeline__date-heading" id="bench-day">2 October 2026 · Newest first</h3><ol class="sk-timeline sk-timeline--compact"><li class="sk-timeline__event" data-pending><span class="sk-timeline__marker" aria-hidden="true"></span><div class="sk-timeline__content"><p class="sk-timeline__summary">System: review is pending.</p><time class="sk-timeline__meta" datetime="2026-10-02T10:00:00Z">10:00 UTC</time></div></li><li class="sk-timeline__event" data-failed><span class="sk-timeline__marker" aria-hidden="true"></span><div class="sk-timeline__content"><p class="sk-timeline__summary">Import service: upload failed.</p><time class="sk-timeline__meta" datetime="2026-10-02T09:00:00Z">09:00 UTC</time><details class="sk-timeline__detail"><summary>Failure details</summary><p>The connection closed. The source file was preserved for retry.</p></details></div></li><li class="sk-timeline__event" data-success><span class="sk-timeline__marker" aria-hidden="true"></span><div class="sk-timeline__content"><p class="sk-timeline__summary">Ana Silva: document created.</p><time class="sk-timeline__meta" datetime="2026-10-02T08:00:00Z">08:00 UTC</time></div></li></ol></section></div>`);
  p.section('Implementation checklist', `<ul class="sk-prose"><li>Keep action labels stable while pending; announce the outcome separately.</li><li>Preserve input on failure. Provide a named retry and a cancellation path.</li><li>Undo restores state, not just a message.</li><li>Compare all sizes at narrow container widths and enlarged text.</li></ul>`);
  return p;
}
